OptunaConfig:
  n_startup_trials: 1
  n_trials: 1
  n_jobs: 1
  study_direction: "maximize"
TrainingConfig:
  dynamic_dataset: True
  train_percentage: 1
  threshold_coverage: 100
  load_to_cpu: False
  epochs: 2
ValidationConfig:
  validation:
    val_type: svms
    servers_count: 1
    fail_immediately: True
    PlatformsConfig:
      - name: dotnet
        DatasetConfigs:
          - dataset_base_path: ../maps/DotNet/Maps/Root/bin/Release/net7.0
            dataset_description: ../workflow/dataset_for_tests_net.json
        SVMSInfo:
          - name: VSharp
            launch_command: dotnet VSharp.ML.GameServer.Runner.dll --mode server --port {port}
            min_port: 35000
            max_port: 35050
            server_working_dir: ../GameServers/VSharp/VSharp.ML.GameServer.Runner/bin/Release/net7.0
      - name: java
        DatasetConfigs:
          - dataset_base_path: ../maps/Java/Maps/
            dataset_description: ../workflow/dataset_for_tests_java.json
        SVMSInfo:
          - name: usvm
            launch_command: java -jar -DLOG_DIR=$PWD app.jar --mode server --port {port}
            min_port: 35100
            max_port: 35150
            server_working_dir: ../GameServers/usvm/usvm-ml-gameserver/build/libs/
MLFlowConfig:
  tracking_uri: http://127.0.0.1:8080
  experiment_name: CI
