- SVMConfig:
    name: VSharp
    count: 1
    launch_command: dotnet VSharp.ML.GameServer.Runner.dll --mode server --port {port}
    min_port: 35000
    max_port: 36000
    server_working_dir: ../GameServers/VSharp/VSharp.ML.GameServer.Runner/bin/Release/net7.0
  DatasetConfig:
    dataset_base_path: ../maps/DotNet/Maps/Root/bin/Release/net7.0
    dataset_description: ../workflow/dataset_for_tests.json
  OptunaConfig:
    n_startup_trials: 1
    n_trials: 1
  TrainConfig:
    epochs: 2
