OptunaConfig:
  n_startup_trials: 1
  n_trials: 1
  n_jobs: 1
  study_direction: "minimize"
TrainingConfig:
  dynamic_dataset: False
  train_percentage: 1
  threshold_coverage: 100
  load_to_cpu: False
  epochs: 2
ValidationConfig:
  validation_mode:
    val_type: loss
    batch_size: 4
MLFlowConfig:
  tracking_uri: http://127.0.0.1:8080
  experiment_name: CI
