name: agent_env
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - blas=2.116
  - blas-devel=3.9.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfgv=3.3.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - dataclasses-json=0.5.7
  - distlib=0.3.6
  - ffmpeg=4.2.2
  - filelock=3.9.0
  - flit-core=3.6.0
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=68.1
  - identify=2.5.19
  - idna=3.4
  - importlib-metadata=6.0.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libidn2=2.3.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.21
  - libopus=1.3
  - libpng=1.6.39
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvpx=1.10.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - marshmallow=3.19.0
  - marshmallow-enum=1.5.1
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - nettle=3.7.3
  - nodeenv=1.7.0
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openblas=0.3.21
  - openh264=1.8.0
  - openssl=1.1.1t
  - packaging=22.0
  - pandas=1.5.3
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=2.5.2
  - pre-commit=2.20.0
  - pre_commit=2.20.0
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - pytorch=1.13.1
  - pytz=2022.7
  - pyyaml=6.0
  - readline=8.2
  - requests=2.28.1
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - stringcase=1.2.0
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - typing_extensions=4.4.0
  - typing_inspect=0.8.0
  - tzdata=2022g
  - ukkonen=1.0.1
  - urllib3=1.26.14
  - virtualenv=20.20.0
  - websocket-client=1.5.1
  - wheel=0.38.4
  - x264=1!152.20180806
  - xz=5.2.10
  - yaml=0.2.5
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - jinja2==3.1.2
      - joblib==1.2.0
      - markupsafe==2.1.2
      - psutil==5.9.4
      - pyparsing==3.0.9
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - threadpoolctl==3.1.0
      - torch-geometric==2.2.0
      - torch-scatter==2.1.0
      - torch-sparse==0.6.16
      - tqdm==4.65.0
