name: Run python tests

on: [pull_request]

jobs:
  build-and-launch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install poetry
        run: |
          pip install poetry
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.8"
          cache: "poetry" 

      - name: Install dependencies
        run: |
          poetry install

      - name: Run tests
        working-directory: ./AIAgent
        run: |
          poetry run pytest tests -sv
